extends Node
## Tiny audio manager: one-shot sound effects and the context-aware soundtrack (the nature
## ambience by place and hour is scripts/world/ambience.gd, on the "Ambience" bus).
## Sound effects are generated by tools/make_audio.py into assets/audio/; the soundtrack
## (assets/audio/music_<name>.ogg: seamless title/day/evening/night/indoor loops plus the
## rare/newday stingers) by tools/make_music.py. Music plays on the "Music" bus and is
## picked from the game state about once a second (title screen, hour of the day, inside
## a house), with equal-power crossfades; a track left and re-entered resumes where it was.

const SOUNDS := ["click", "coin", "chop", "plant", "harvest", "bad", "quest", "pop", "whoosh", "step", "door", "cash"]
## the tracks are mastered to -20 LUFS; this sits them under the sound effects and voices
const MUSIC_DB := -6.0
const XFADE := 3.5             # s, crossfade between two context tracks
const FADE_IN := 1.5           # s, fade-in from silence
const FADE_OUT := 0.7          # s, when the music is switched off
const CONTEXT_POLL := 1.0      # s between context checks
const EVENING_START := 17.0    # day 6-17, evening 17-19.5, night after
const NIGHT_START := 19.5
const MUSIC_TRACKS := ["title", "day", "evening", "night", "indoor"]
## stingers (short jingles over the ducked loop) -> sound effect used when the music is off
const STINGERS := {"rare": "quest", "newday": ""}
const STINGER_DUCK_DB := -12.0
## duck_voice(): bus attenuation while a voice line plays
const VOICE_DUCK_MUSIC_DB := -7.0
const VOICE_DUCK_AMBIENCE_DB := -4.0
const VOICE_DUCK_TIME := 0.3
const DECKS := 3               # music players: two crossfading plus one spare for quick changes

var _streams := {}
var _players: Array[AudioStreamPlayer] = []
var music_on := true
var sfx_on := true

var _decks: Array[AudioStreamPlayer] = []
var _deck_track: Array[String] = []
var _deck_pos: Array[float] = []     # fade position 0..1 (gain = sin(pos * PI/2): equal power)
var _deck_speed: Array[float] = []   # fade speed per second (+ in, - out, 0 = steady)
var _track := ""                     # the track the context asks for ("" = silence)
var _forced := ""                    # set_context() override
var _resume := {}                    # track -> playback position to continue from
var _music_cache := {}
var _stinger: AudioStreamPlayer
var _stinger_left := 0.0
var _duck := 1.0                     # stinger duck (linear gain on the loops)
var _voice_on := false
var _voice_k := 0.0                  # 0..1 voice duck amount (ramped)
var _ctx_t := CONTEXT_POLL - 0.3
var _music_bus := -1
var _amb_bus := -1
var _music_bus_db := 0.0
var _amb_bus_db := 0.0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for s in SOUNDS:
		var path := "res://assets/audio/%s.wav" % s
		if ResourceLoader.exists(path):
			_streams[s] = load(path)
	var sfx_bus := "SFX" if AudioServer.get_bus_index("SFX") != -1 else "Master"
	for i in 8:
		var p := AudioStreamPlayer.new()
		p.bus = sfx_bus
		add_child(p)
		_players.append(p)
	_music_bus = AudioServer.get_bus_index("Music")
	var mbus := "Music" if _music_bus != -1 else "Master"
	if _music_bus != -1:
		_music_bus_db = AudioServer.get_bus_volume_db(_music_bus)
	_amb_bus = AudioServer.get_bus_index("Ambience")
	if _amb_bus != -1:
		_amb_bus_db = AudioServer.get_bus_volume_db(_amb_bus)
	for i in DECKS:
		var d := AudioStreamPlayer.new()
		d.bus = mbus
		d.volume_db = -80.0
		add_child(d)
		_decks.append(d)
		_deck_track.append("")
		_deck_pos.append(0.0)
		_deck_speed.append(0.0)
	_stinger = AudioStreamPlayer.new()
	_stinger.bus = mbus
	add_child(_stinger)
	GS.day_started.connect(_on_day_started)


func play(name: String, pitch := 1.0, volume_db := 0.0) -> void:
	if not sfx_on or not _streams.has(name):
		return
	for p in _players:
		if not p.playing:
			p.stream = _streams[name]
			p.pitch_scale = pitch * randf_range(0.96, 1.04)
			p.volume_db = volume_db
			p.play()
			return


# ------------------------------------------------------------------ music
func start_music() -> void:
	_ctx_t = CONTEXT_POLL   # re-check the context on the next frame


func set_music(on: bool) -> void:
	music_on = on
	if not on:
		_stinger.stop()
		_stinger_left = 0.0
	_update_context()


## Forces a track ("title", "day", "evening", "night", "indoor"); "" = back to automatic.
func set_context(ctx: String) -> void:
	_forced = ctx
	_update_context()


## The track the music is on (or fading to); "" when silent.
func current_track() -> String:
	return _track


## Lowers the music (~7 dB) and ambience (~4 dB) smoothly while a voice line plays.
func duck_voice(on: bool) -> void:
	_voice_on = on


## Short jingle over the ducked loop: "rare" (SR/SSR catch), "newday". With the music
## switched off the matching sound effect plays instead.
func stinger(name: String) -> void:
	var s: AudioStream = _music_stream(name) if music_on else null
	if s == null:
		var fb: String = STINGERS.get(name, "")
		if fb != "":
			play(fb)
		return
	_stinger.stream = s
	_stinger.volume_db = MUSIC_DB
	_stinger.play()
	_stinger_left = maxf(0.5, s.get_length() - 0.5)


func _on_day_started(_report: Array) -> void:
	_resume.clear()    # a new day starts every track from its top
	stinger("newday")


func _context() -> String:
	var w := get_tree().current_scene
	if w == null:
		return "title"
	var st = w.get("state")
	if st == null or st == "title":
		return "title"
	var ins = w.get("inside")
	if ins is String and ins != "":
		return "indoor"
	var h: float = GS.hour
	if h >= GS.DAY_START and h < EVENING_START:
		return "day"
	if h >= EVENING_START and h < NIGHT_START:
		return "evening"
	return "night"


func _update_context() -> void:
	var want := ""
	if music_on:
		want = _forced if _forced != "" else _context()
	if want != _track:
		_switch(want)


func _switch(track: String) -> void:
	var silent := true
	for i in DECKS:
		if _deck_track[i] != "" and _deck_pos[i] > 0.05:
			silent = false
	_track = track
	for i in DECKS:
		if _deck_track[i] != "" and _deck_track[i] != track:
			_deck_speed[i] = -1.0 / (FADE_OUT if track == "" else XFADE)
	if track == "":
		return
	var s := _music_stream(track)
	if s == null:
		return
	var i := _deck_track.find(track)
	if i == -1:
		# the quietest deck takes the new track
		i = 0
		for k in DECKS:
			if _deck_pos[k] < _deck_pos[i]:
				i = k
		if _deck_track[i] != "":
			_park(i)
		var d := _decks[i]
		d.stream = s
		d.volume_db = -80.0
		_deck_track[i] = track
		_deck_pos[i] = 0.0
		d.play(float(_resume.get(track, 0.0)))
	_deck_speed[i] = 1.0 / (FADE_IN if silent else XFADE)


func _park(i: int) -> void:
	## a deck faded out: remember where its track was, stop it
	var d := _decks[i]
	var t := _deck_track[i]
	if d.playing and t != "" and t != "title":
		_resume[t] = d.get_playback_position()
	d.stop()
	d.volume_db = -80.0
	_deck_track[i] = ""
	_deck_pos[i] = 0.0
	_deck_speed[i] = 0.0


func _music_stream(name: String) -> AudioStream:
	if _music_cache.has(name):
		return _music_cache[name]
	var s: AudioStream = null
	var path := "res://assets/audio/music_%s.ogg" % name
	if ResourceLoader.exists(path):
		s = load(path)
		if s is AudioStreamOggVorbis:
			(s as AudioStreamOggVorbis).loop = not STINGERS.has(name)
	_music_cache[name] = s
	return s


func _prefetch() -> void:
	## loads one not-yet-loaded track per context poll, so a later switch never stalls
	for n in MUSIC_TRACKS + STINGERS.keys():
		if not _music_cache.has(n):
			_music_stream(n)
			return


func _process(delta: float) -> void:
	_ctx_t += delta
	if _ctx_t >= CONTEXT_POLL:
		_ctx_t = 0.0
		_update_context()
		if music_on:
			_prefetch()
	var dirty := false
	for i in DECKS:
		if _deck_speed[i] != 0.0:
			_deck_pos[i] = clampf(_deck_pos[i] + _deck_speed[i] * delta, 0.0, 1.0)
			dirty = true
			if _deck_pos[i] <= 0.0 and _deck_speed[i] < 0.0:
				_park(i)
			elif _deck_pos[i] >= 1.0 and _deck_speed[i] > 0.0:
				_deck_speed[i] = 0.0
	if _stinger_left > 0.0:
		_stinger_left -= delta
	var duck_to := db_to_linear(STINGER_DUCK_DB) if _stinger_left > 0.0 else 1.0
	if _duck != duck_to:
		_duck = move_toward(_duck, duck_to, delta * (4.0 if duck_to < _duck else 0.8))
		dirty = true
	if dirty:
		for i in DECKS:
			if _deck_track[i] != "":
				var g := sin(_deck_pos[i] * PI * 0.5) * _duck
				_decks[i].volume_db = MUSIC_DB + linear_to_db(maxf(g, 0.0001))
	var vt := 1.0 if _voice_on else 0.0
	if _voice_k != vt:
		_voice_k = move_toward(_voice_k, vt, delta / VOICE_DUCK_TIME)
		var k := smoothstep(0.0, 1.0, _voice_k)
		if _music_bus != -1:
			AudioServer.set_bus_volume_db(_music_bus, _music_bus_db + VOICE_DUCK_MUSIC_DB * k)
		if _amb_bus != -1:
			AudioServer.set_bus_volume_db(_amb_bus, _amb_bus_db + VOICE_DUCK_AMBIENCE_DB * k)


func _exit_tree() -> void:
	# a stream still playing when the game quits is held by the AudioServer past the
	# autoload's own teardown ("ObjectDB instances leaked" / "resources still in use"
	# at every exit, hiding real leaks): stop and drop everything first
	for p: AudioStreamPlayer in _players + _decks + [_stinger]:
		if p:
			p.stop()
			p.stream = null
	_streams.clear()
	_music_cache.clear()
